tasks:
    - name: Setup
      before: |
          # Install Asciidoctor
          # needs to be in before since gitpod resets the container every time
          gem install asciidoctor

      init: |
          # Add .env file
          cp sample.env .env

          # Install npm dependencies
          # npm installs dependencies to the working folder, which are persistent across restarts
          npm install

          # exit to prevent extra terminal window
          exit

vscode:
    extensions:
        - esbenp.prettier-vscode
        - asciidoctor.asciidoctor-vscode
        - mikestead.dotenv
        - redhat.vscode-yaml
        - streetsidesoftware.code-spell-checker

ports:
    - port: 5000
      onOpen: open-browser
      visibility: public
