tasks:
    - name: Setup
      init: |
          # Add .env file
          cp sample.env .env

          # Install Asciidoctor
          gem install asciidoctor

          # Install npm dependencies
          npm install

          # exit to prevent extra terminal window
          exit

vscode:
    extensions:
        - esbenp.prettier-vscode
        - asciidoctor.asciidoctor-vscode
        - mikestead.dotenv
        - redhat.vscode-yaml
        - streetsidesoftware.code-spell-checker

ports:
    - port: 5000
      onOpen: open-browser
      visibility: public
