Date: 27-03-2021

Duration: 5 hr 43 min 

==== Topics Discussed

* Jitsi got a UI refresh with some bugs as well :joy: :party_ball: .
* @*Jai Kumar Dewani* told us his interview experience and then we talked about how the interview process goes like.
* @*Saurabh Daware* explained us what is DOM and difference between DOM and virtual DOM.
* Along with flexing his Apple products :stuck_out_tongue_wink: @*Chirag Nayyar* gave an insight about his life and how he manages everything alone.
* @*Chirag Nayyar* told us about INA and history of singapore and why tamil is official language there.
* We also had a discussion on ARM server and thier adoption in market.
* @*Chirag Nayyar* gave us task to learn about AD (Active directory) and GitOps.
* We also talked about the difference between Vulkan and OpenGL
* A few questions like What is DevOps and What is open stack were also answered.



See you all next time on <time:2021-04-3T22:30:00+05:30>!
Do join in!

link:/user_uploads/29573/YVlNi92npKW-JEXV0jFmigto/Screenshot-105.png[Meet Screenshot.png]
