Date: 26-07-2025

Duration: 1 hr 31 mins

==== Topics Discussed

* Everyone gave a short intro of themselves
    ** Naufil, a final year B.Tech student at Sardar Patel Institute of Technology, works on full-stack development and is an ex-Indian Navy SWE.
    ** Ankush Kapoor, currently in his 2nd year of Computer Engineering, codes mostly in Python and C. He is interested in systems and AI/ML and is currently learning about OS.
    ** Bhavesh, currently in his 3rd year at TSEC, codes mostly in Python and C. He is currently exploring Python internals, working on a B+ Tree for his DBMS project, and also working on Django and React.js for his personal project.
* Harsh Jain asked about FFIs for using Rust code (backend) without using a C bridge.
    ** Darshan suggested using DLL.
        *** link:https://github.com/SeanPesce/DLL_Wrapper_Generator[DLL Wrapper Generator GitHub repo^]
* Mohit shared about his initial journey, to-dos for his PhD, and about explainable AI. He is going to build a model for DRDO.
    ** Mohit also shared his opinion on BITS Pilani.
* Kartik Jain showcased his project: Art Gallery One.
    ** He talked about how he used an Amazon S3 bucket for storage and deployed it with a Redis DB.
    ** Mohit Shetty suggested to him how he can use AI in his project for face recognition.
* Atharva talked about his cybersecurity project.
    ** He talked about how he built a monitoring system using AI to monitor the server.
* Additional links:
    ** link:https://en.wikipedia.org/wiki/Foreign_function_interface[Foreign function interface - Wikipedia^]
    ** link:https://semaphore.io/blog/what-is-canary-deploymen[What is Canary Deployment? - Semaphore^]
    ** link:https://backstage.io[Backstage - An open platform for building developer portals^]
    ** link:https://meshery.io[Meshery - The Cloud Native Manager^]
    ** link:https://mpstme.pics[MPSTME Pics^]
    ** link:https://catchup.ourtech.community/showcase[Our Tech Community Showcase^]
    ** link:https://www.cncf.io[Cloud Native Computing Foundation^]
