Date: 19-12-2020

Duration: 5 hr 35 min 

==== Topics Discussed

* College syllabus
* How the teacher's role is so pivotal in a student being able to gain interest in a subject
* @*sirus* showed us his simple feedback-collecting web app that he made using Flutter Web and Firebase. (https://aboutme-55236.web.app/)
* We were joined by https://www.linkedin.com/in/chiragnayyar/[Chirag Nayyar] sir who told us a LOT about
 ** his life experiences
 ** how we could be more confident and not lower our self-esteem when faced with failures
 ** why the basics are more important than the evolving technologies
 ** techniques to learn things in general and in Cloud. @*Milan Chandiramani*, @*Tanay Kamath* and others asked him doubts as well.
+
NOTE: I have posted my summary of Chirag Sir's talks on tips for getting started with Cloud in the #*cloud>general* stream-topic. Do have a read!
* We talked about the amazing companies Nikola and Tesla.
* We also helped @*Pranav Dani* apply for an internship! 😂
