#!/bin/sh

set -eu;

script_dir=$(dirname "${0}");
base_dir=$(realpath "${script_dir}/..");
summary_dir="${base_dir}/summary";

out_dir="${1:-build}";

echo "Building summary pages using Asciidoctor Jet...";

# Cleanup old builds
rm -rf "${out_dir}";
rm -f "${summary_dir}/autogenerated-combined-summary.adoc";

# Copy public files to output directory
cp -r "${base_dir}/public" "${out_dir}";
cp -r "${summary_dir}/static/img/" "${out_dir}/img/summary";

# Reverse order so summaries are newest to oldest
BUILD_SUMMARY_DIRS="";
for path in "${summary_dir}/sessions/"*; do
	if [ -d "${path}" ]; then
		BUILD_SUMMARY_DIRS="${path} ${BUILD_SUMMARY_DIRS}";
	fi;
done;

# Store all built catchups for quick lookup in edge functions
built_catchup_numbers="";

# Build individual summary pages
for path in ${BUILD_SUMMARY_DIRS}; do
	if [ -d "${path}" ]; then
		catchup_number=${path##*/};
		catchup_display_number=$(printf "%.0f" "${catchup_number}");

		# If summary/sessions/${catchup_number}/summary-template.adoc exists,
		# then use it, else use the default template
		summary_template="sessions/${catchup_number}/summary-template.adoc";
		if [ ! -f "${summary_dir}/${summary_template}" ]; then
			summary_template="summary-template.adoc";
		fi;

		# Use the first image named `${catchup_number}.*`
		catchup_image_folder="${summary_dir}/static/img";
		catchup_image_extension="";
		# Only search for an image extension if used in the template
		if grep -Fq "{catchup_image_extension}" "${summary_dir}/${summary_template}"; then
			for image in "${catchup_image_folder}/${catchup_number}."*; do
				if [ -e "${image}" ]; then
					if [ -z "${catchup_image_extension}" ]; then
						# remove `${catchup_image_folder}/${catchup_number}.` from path,
						# leaving only the extension
						catchup_image_extension=${image##*"${catchup_image_folder}"/"${catchup_number}".};
					else
						echo "warning: found multiple images for catchup #${catchup_number}, ignoring ${image}";
					fi;
				fi;
			done;
			if [ -z "${catchup_image_extension}" ]; then
				echo "error: could not find image for catchup #${catchup_number} in: ${catchup_image_folder}";
				exit 1;
			fi;
		fi;

		# Add template to combined summary page
		{
			echo ":catchup_number:          ${catchup_number}";
			echo ":catchup_display_number:  ${catchup_display_number}";
			echo ":catchup_image_extension: ${catchup_image_extension}";
			echo "include::${summary_template}[]";
			echo "";
		} >> "${summary_dir}/autogenerated-combined-summary.adoc";

		asciidoctor \
			-a webfonts! \
			-a "catchup_number=${catchup_number}" \
			-a "catchup_display_number=${catchup_display_number}" \
			-a "catchup_image_extension=${catchup_image_extension}" \
			-a "summary_file=${summary_template}" \
			-o "${out_dir}/summary/${catchup_display_number}.html" \
			"${summary_dir}/individual-summary.adoc";

		# Lazy load images
		sed -i -e "s/<img/<img loading=\"lazy\"/g" "${out_dir}/summary/${catchup_display_number}.html";

		# Add current summary to list of built catchups
		built_catchup_numbers="${built_catchup_numbers}\n  ${catchup_display_number},";
	fi;
done;

# Save built catchup numbers to netlify functions folder
printf "export default [${built_catchup_numbers}\n];\n" \
	> "${base_dir}/netlify/edge-functions/built-catchup-numbers.ts";

# Build combined summary site
asciidoctor \
	-a webfonts! \
	-o "${out_dir}/summary/index.html" \
	"${summary_dir}/combined-summary.adoc";
# Lazy load images
sed -i -e 's/<img/<img loading="lazy"/g' "${out_dir}/summary/index.html";

echo "Summary pages build complete!";
echo;
