Date: 02-01-2021

Duration: 7 hr

==== Topics Discussed

* General introductions.
* @*Harsh Kapadia* shared an issue that Tushar had raised in one of his repos and asked people for their opinions. Tushar was then told to open a PR as everyone liked his suggestions!
* @*Harsh Kapadia* showed everyone PowerToys by Microsoft, a nice utility for Windows and its features. It's really handy!
* @*sirus* had opened a PR in the Flutter repo and showed us that. He will keep us posted on the progress with that.
* @*Pranav Dani* asked about hackathons as he has no experience with them and everyone shared their perspectives. There were a lot of funny hackathon stories shared as well 😂
* We talked about back end frameworks like Django and Node.js and compared them.
* We saw some https://threejs.org/[Three.js] projects as well.
* We watched random videos on YouTube lol
* We also saw some poorly written research papers.

==== Project Showcased

 * https://twitter.com/THESPACELAD[Arpit Anand], an Android app dev from Kolkata showed us his new note taking app called https://play.google.com/store/apps/details?id=com.arpit.notify[Feather Notes].
 * @*sirus* showed us the updates he made in his Flutter poem writing (and picture generation) app called _Heartry_.
 * https://twitter.com/saurabhcodes[Saurabh Daware] showed us his rocket game called https://eotm.ml/[Edge of The Matrix] that works using mobile sensors. He emulated the sensor in the browser using the sensors tab in the DevTools. We didn't even know that such a tab existed! It is a PWA as well!
 * @*Anushka Bhagchandani* showed us her web app. She had done the front end for it and it looked so good! The back end was in PHP.
 * @*Jai Kumar Dewani* showed us a lot of his projects like his WhatsApp script, his youtube-dl web app and more...
 * @*Dheeraj Lalwani* showed us a web app that he made in a hackathon. It was a hospital management system. He had used Bootstrap and Django.


We were joined by https://twitter.com/saurabhcodes[Saurabh Daware] and https://twitter.com/THESPACELAD[Arpit Anand] as well!

With the completion of the 8th session, I am so proud to announce that OTC CatchUp has completed two months of continuous weekly sessions! Also, OTC is almost a year old now! 🥳

Thank you so much to everyone who came for any of the sessions! I'll be announcing the date for the next session soon!

